import type { Stats } from "node:fs";
import {
  chmod,
  lstat,
  mkdtemp,
  mkdir,
  open,
  opendir,
  realpath,
  rm,
} from "node:fs/promises";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { canonicalize, digestJson, isSha256Digest, sha256Digest, type JsonValue } from "@jevyr/protocol";
import {
  normalizeJevyrRelativePath,
  privateKeyContentReason,
  type JevyrIgnorePolicy,
} from "./ignore-policy.js";

export const CANDIDATE_BLUEPRINT_PROTOCOL = "jevyr.candidate-blueprint/1" as const;
export const CANDIDATE_MATERIALIZATION_PROTOCOL = "jevyr.candidate-materialization/1" as const;
export const CANDIDATE_TREE_PROTOCOL = "jevyr.candidate-tree/1" as const;

export const HARD_CANDIDATE_BLUEPRINT_LIMITS = Object.freeze({
  maxFiles: 256,
  maxFileBytes: 1_000_000,
  maxTotalBytes: 8_000_000,
  maxPathBytes: 4_096,
  maxCommandArgs: 64,
  maxArgumentBytes: 4_096,
  maxCommandBytes: 16_384,
});

export interface CandidateBlueprintLimits {
  readonly maxFiles: number;
  readonly maxFileBytes: number;
  readonly maxTotalBytes: number;
  readonly maxPathBytes: number;
  readonly maxCommandArgs: number;
  readonly maxArgumentBytes: number;
  readonly maxCommandBytes: number;
}

export interface CandidateBlueprintLimitOverrides {
  readonly maxFiles?: number;
  readonly maxFileBytes?: number;
  readonly maxTotalBytes?: number;
  readonly maxPathBytes?: number;
  readonly maxCommandArgs?: number;
  readonly maxArgumentBytes?: number;
  readonly maxCommandBytes?: number;
}

export interface CandidateBlueprintSourceFile {
  readonly path: string;
  readonly content: string;
}

export interface CandidateBlueprintFile extends CandidateBlueprintSourceFile {
  readonly byteLength: number;
  readonly digest: string;
}

export interface CandidateCommandProposal {
  readonly executable: string;
  readonly args: readonly string[];
  /** This value is generated by Jevyr and cannot be supplied by model output. */
  readonly shell: false;
  /** A proposal has no oracle, verdict, execution, or policy authority. */
  readonly authority: "proposal-only";
}

export interface CompiledCandidateBlueprint {
  readonly protocol: typeof CANDIDATE_BLUEPRINT_PROTOCOL;
  readonly files: readonly CandidateBlueprintFile[];
  readonly command?: CandidateCommandProposal;
  readonly ignorePolicyDigest: string;
  readonly limits: CandidateBlueprintLimits;
  readonly blueprintDigest: string;
}

export interface CandidateMaterializedFile {
  readonly path: string;
  readonly byteLength: number;
  readonly digest: string;
}

export interface CandidateMaterialization {
  readonly protocol: typeof CANDIDATE_MATERIALIZATION_PROTOCOL;
  /** Random, newly-created directory. This path is deliberately absent from the digest. */
  readonly root: string;
  readonly blueprintDigest: string;
  readonly files: readonly CandidateMaterializedFile[];
  readonly fileCount: number;
  readonly byteLength: number;
  readonly materializationDigest: string;
  readonly commandProposal?: CandidateCommandProposal;
}

/**
 * A path-free identity for the exact regular-file tree handed across the
 * Forge boundary. Directories are implied by canonical file paths, so this
 * digest is stable across fresh per-cell roots.
 */
export function candidateTreeDigest(filesInput: readonly CandidateMaterializedFile[]): string {
  const files = [...filesInput]
    .map((file) => Object.freeze({ path: file.path, byteLength: file.byteLength, digest: file.digest }))
    .sort((left, right) => compareText(left.path, right.path));
  const directorySet = new Set<string>();
  for (const file of files) {
    const parts = file.path.split("/");
    for (let index = 1; index < parts.length; index += 1) directorySet.add(parts.slice(0, index).join("/"));
  }
  const directories = Object.freeze([...directorySet].sort(compareText));
  return digestJson({
    protocol: CANDIDATE_TREE_PROTOCOL,
    directories,
    files,
  } as unknown as JsonValue);
}

/** Recomputes the path-free candidate materialization commitment. */
export function candidateMaterializationDigest(
  blueprintDigest: string,
  filesInput: readonly CandidateMaterializedFile[],
): string {
  const files = Object.freeze([...filesInput]
    .map((file) => Object.freeze({ path: file.path, byteLength: file.byteLength, digest: file.digest }))
    .sort((left, right) => compareText(left.path, right.path)));
  return digestJson({
    protocol: CANDIDATE_MATERIALIZATION_PROTOCOL,
    blueprintDigest,
    files,
    fileCount: files.length,
    byteLength: files.reduce((sum, file) => sum + file.byteLength, 0),
  } as unknown as JsonValue);
}

export type CandidateBlueprintErrorCode =
  | "collision"
  | "filesystem-integrity"
  | "ignored-path"
  | "integrity"
  | "invalid-command"
  | "invalid-content"
  | "invalid-path"
  | "invalid-shape"
  | "limit"
  | "secret-content"
  | "unsafe-destination"
  | "unknown-field";

export class CandidateBlueprintError extends Error {
  readonly code: CandidateBlueprintErrorCode;

  constructor(code: CandidateBlueprintErrorCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "CandidateBlueprintError";
    this.code = code;
  }
}

type JsonRecord = Record<string, unknown>;

const LIMIT_FIELDS = Object.freeze([
  "maxFiles",
  "maxFileBytes",
  "maxTotalBytes",
  "maxPathBytes",
  "maxCommandArgs",
  "maxArgumentBytes",
  "maxCommandBytes",
] as const);

const CREDENTIAL_CONTENT_PATTERNS = Object.freeze([
  /\bAKIA[0-9A-Z]{16}\b/u,
  /\bgithub_pat_[A-Za-z0-9_]{20,}\b/u,
  /\bgh[pousr]_[A-Za-z0-9]{30,}\b/u,
  /\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/u,
  /\bxox[baprs]-[A-Za-z0-9-]{20,}\b/u,
  /(?:api[_-]?key|access[_-]?token|auth[_-]?token|client[_-]?secret|password|passwd)\s*[:=]\s*["']?[A-Za-z0-9_+\/=.-]{12,}/iu,
]);

const WINDOWS_RESERVED_STEM = /^(?:con|prn|aux|nul|clock\$|conin\$|conout\$|com[1-9¹²³]|lpt[1-9¹²³])$/iu;
const INVALID_PORTABLE_PATH_CHARACTER = /[<>:"|?*\u0000-\u001f\u007f]/u;
const INVALID_ARGUMENT_CHARACTER = /[\u0000-\u001f\u007f]/u;
const COMMAND_NAME = /^[A-Za-z0-9][A-Za-z0-9._+-]*$/u;

function fail(code: CandidateBlueprintErrorCode, message: string, cause?: unknown): never {
  throw new CandidateBlueprintError(code, message, cause === undefined ? undefined : { cause });
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function isPlainRecord(value: unknown, context: string): JsonRecord {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return fail("invalid-shape", `${context} must be a JSON object.`);
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    return fail("invalid-shape", `${context} must be a plain JSON object.`);
  }
  const record = value as JsonRecord;
  for (const key of Reflect.ownKeys(record)) {
    if (typeof key !== "string") fail("invalid-shape", `${context} contains a non-JSON property.`);
    const descriptor = Object.getOwnPropertyDescriptor(record, key);
    if (descriptor === undefined || !descriptor.enumerable || !("value" in descriptor) || descriptor.value === undefined) {
      fail("invalid-shape", `${context}.${key} is not a JSON property.`);
    }
  }
  return record;
}

function assertExactKeys(
  record: JsonRecord,
  allowed: readonly string[],
  required: readonly string[],
  context: string,
): void {
  const allowedSet = new Set(allowed);
  for (const key of Object.keys(record)) {
    if (!allowedSet.has(key)) fail("unknown-field", `${context} contains unknown field ${JSON.stringify(key)}.`);
  }
  for (const key of required) {
    if (!Object.hasOwn(record, key)) fail("invalid-shape", `${context} is missing required field ${JSON.stringify(key)}.`);
  }
}

function jsonArray(value: unknown, context: string): readonly unknown[] {
  if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) {
    return fail("invalid-shape", `${context} must be a JSON array.`);
  }
  const ownKeys = Reflect.ownKeys(value);
  if (ownKeys.some((key) => typeof key !== "string" || (key !== "length" && !/^(?:0|[1-9]\d*)$/u.test(key)))) {
    return fail("invalid-shape", `${context} contains a non-JSON array property.`);
  }
  for (let index = 0; index < value.length; index += 1) {
    if (!Object.hasOwn(value, index) || value[index] === undefined) {
      fail("invalid-shape", `${context} must not contain holes or undefined values.`);
    }
  }
  return value;
}

function assertWellFormedUnicode(value: string, context: string, code: CandidateBlueprintErrorCode): void {
  for (let index = 0; index < value.length; index += 1) {
    const unit = value.charCodeAt(index);
    if (unit >= 0xd800 && unit <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) fail(code, `${context} contains an unpaired Unicode surrogate.`);
      index += 1;
    } else if (unit >= 0xdc00 && unit <= 0xdfff) {
      fail(code, `${context} contains an unpaired Unicode surrogate.`);
    }
  }
}

function positiveBoundedInteger(value: unknown, maximum: number, context: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) > maximum) {
    return fail("limit", `${context} must be a positive safe integer no greater than ${maximum}.`);
  }
  return value as number;
}

function normalizeLimits(input: CandidateBlueprintLimitOverrides = {}): CandidateBlueprintLimits {
  const record = isPlainRecord(input, "candidate blueprint limits");
  assertExactKeys(record, LIMIT_FIELDS, [], "candidate blueprint limits");
  const values = Object.fromEntries(LIMIT_FIELDS.map((field) => [
    field,
    positiveBoundedInteger(record[field] ?? HARD_CANDIDATE_BLUEPRINT_LIMITS[field], HARD_CANDIDATE_BLUEPRINT_LIMITS[field], `limits.${field}`),
  ])) as unknown as CandidateBlueprintLimits;
  return Object.freeze(values);
}

function validateCompiledLimits(value: unknown): CandidateBlueprintLimits {
  const record = isPlainRecord(value, "compiled candidate limits");
  assertExactKeys(record, LIMIT_FIELDS, LIMIT_FIELDS, "compiled candidate limits");
  return normalizeLimits(record as CandidateBlueprintLimitOverrides);
}

function collisionKey(path: string): string {
  return path.normalize("NFKC").toLowerCase();
}

function windowsReservedName(value: string): boolean {
  const stem = (value.split(".")[0] ?? value).replace(/[ .]+$/u, "");
  return WINDOWS_RESERVED_STEM.test(stem);
}

function candidatePath(path: unknown, limits: CandidateBlueprintLimits): string {
  if (typeof path !== "string" || path.length === 0) fail("invalid-path", "Candidate file path must be a non-empty string.");
  assertWellFormedUnicode(path, "Candidate file path", "invalid-path");
  if (
    path.includes("\\") ||
    path.startsWith("/") ||
    path.startsWith("//") ||
    /^[A-Za-z]:/u.test(path) ||
    isAbsolute(path)
  ) {
    fail("invalid-path", `Candidate path is absolute or non-portable: ${path}`);
  }
  let normalized: string;
  try {
    normalized = normalizeJevyrRelativePath(path);
  } catch (error) {
    return fail("invalid-path", `Candidate path is unsafe: ${path}`, error);
  }
  if (normalized !== path || path.normalize("NFC") !== path) {
    fail("invalid-path", `Candidate path is not in canonical portable form: ${path}`);
  }
  if (Buffer.byteLength(path, "utf8") > limits.maxPathBytes) {
    fail("limit", `Candidate path exceeds ${limits.maxPathBytes} UTF-8 bytes: ${path}`);
  }
  for (const segment of path.split("/")) {
    if (
      segment.length === 0 ||
      segment !== segment.trim() ||
      segment.endsWith(".") ||
      INVALID_PORTABLE_PATH_CHARACTER.test(segment) ||
      windowsReservedName(segment) ||
      Buffer.byteLength(segment, "utf8") > 255
    ) {
      fail("invalid-path", `Candidate path has a non-portable segment: ${path}`);
    }
  }
  if (path === ".jevyrignore" || path === ".jevyr-subjects" || path.startsWith(".jevyr-subjects/")) {
    fail("ignored-path", "Candidate output cannot replace Jevyr control files or its sealed-subject mount.");
  }
  return path;
}

function assertPathAllowed(path: string, policy: JevyrIgnorePolicy): void {
  const parts = path.split("/");
  for (let index = 1; index < parts.length; index += 1) {
    const parent = parts.slice(0, index).join("/");
    const decision = policy.decide(parent, true);
    if (decision.ignored) {
      fail("ignored-path", `Candidate path ${JSON.stringify(path)} enters ignored directory ${JSON.stringify(parent)} (${decision.reason ?? "policy"}).`);
    }
  }
  const decision = policy.decide(path, false);
  if (decision.ignored) {
    fail("ignored-path", `Candidate path ${JSON.stringify(path)} is forbidden by ${decision.reason ?? "policy"}.`);
  }
}

function sourceContent(value: unknown, path: string, limits: CandidateBlueprintLimits): CandidateBlueprintFile {
  if (typeof value !== "string") fail("invalid-content", `Candidate file ${JSON.stringify(path)} must contain a UTF-8 string.`);
  assertWellFormedUnicode(value, `Candidate file ${JSON.stringify(path)}`, "invalid-content");
  for (let index = 0; index < value.length; index += 1) {
    const unit = value.charCodeAt(index);
    if ((unit < 0x20 && unit !== 0x09 && unit !== 0x0a && unit !== 0x0d) || unit === 0x7f) {
      fail("invalid-content", `Candidate file ${JSON.stringify(path)} contains binary control characters.`);
    }
  }
  const bytes = Buffer.from(value, "utf8");
  if (bytes.byteLength > limits.maxFileBytes) {
    fail("limit", `Candidate file ${JSON.stringify(path)} exceeds ${limits.maxFileBytes} UTF-8 bytes.`);
  }
  if (privateKeyContentReason(bytes) !== undefined || CREDENTIAL_CONTENT_PATTERNS.some((pattern) => pattern.test(value))) {
    fail("secret-content", `Candidate file ${JSON.stringify(path)} appears to contain credential or private-key material.`);
  }
  return Object.freeze({
    path,
    content: value,
    byteLength: bytes.byteLength,
    digest: sha256Digest(bytes),
  });
}

function validatePathSet(files: readonly CandidateBlueprintFile[]): void {
  const fileKeys = new Map<string, string>();
  for (const file of files) {
    const key = collisionKey(file.path);
    const existing = fileKeys.get(key);
    if (existing !== undefined) {
      fail("collision", `Candidate paths collide on a portable case-folded filesystem: ${JSON.stringify(existing)} and ${JSON.stringify(file.path)}.`);
    }
    fileKeys.set(key, file.path);
  }
  for (const file of files) {
    const parts = file.path.split("/");
    for (let index = 1; index < parts.length; index += 1) {
      const prefix = collisionKey(parts.slice(0, index).join("/"));
      const parentFile = fileKeys.get(prefix);
      if (parentFile !== undefined) {
        fail("collision", `Candidate path ${JSON.stringify(file.path)} requires ${JSON.stringify(parentFile)} to be both a file and a directory.`);
      }
    }
  }
}

function parseCommand(value: unknown, limits: CandidateBlueprintLimits): CandidateCommandProposal {
  const record = isPlainRecord(value, "candidate command proposal");
  assertExactKeys(record, ["executable", "args"], ["executable", "args"], "candidate command proposal");
  if (typeof record.executable !== "string") fail("invalid-command", "Candidate command executable must be a string.");
  const executable = record.executable;
  assertWellFormedUnicode(executable, "Candidate command executable", "invalid-command");
  if (
    !COMMAND_NAME.test(executable) ||
    executable === "." ||
    executable === ".." ||
    windowsReservedName(executable) ||
    Buffer.byteLength(executable, "utf8") > 256
  ) {
    fail("invalid-command", "Candidate command executable must be one bounded portable basename, not a path or shell expression.");
  }
  const values = jsonArray(record.args, "candidate command args");
  if (values.length > limits.maxCommandArgs) {
    fail("limit", `Candidate command exceeds ${limits.maxCommandArgs} arguments.`);
  }
  const args: string[] = [];
  let commandBytes = Buffer.byteLength(executable, "utf8");
  for (const [index, value] of values.entries()) {
    if (typeof value !== "string") fail("invalid-command", `Candidate command argument ${index} must be a string.`);
    assertWellFormedUnicode(value, `Candidate command argument ${index}`, "invalid-command");
    if (INVALID_ARGUMENT_CHARACTER.test(value)) {
      fail("invalid-command", `Candidate command argument ${index} contains a control character.`);
    }
    const bytes = Buffer.byteLength(value, "utf8");
    if (bytes > limits.maxArgumentBytes) {
      fail("limit", `Candidate command argument ${index} exceeds ${limits.maxArgumentBytes} UTF-8 bytes.`);
    }
    commandBytes += bytes;
    if (commandBytes > limits.maxCommandBytes) {
      fail("limit", `Candidate command exceeds ${limits.maxCommandBytes} aggregate UTF-8 bytes.`);
    }
    args.push(value);
  }
  return Object.freeze({
    executable,
    args: Object.freeze(args),
    shell: false,
    authority: "proposal-only",
  });
}

function blueprintPayload(
  files: readonly CandidateBlueprintFile[],
  command: CandidateCommandProposal | undefined,
  policyDigest: string,
  limits: CandidateBlueprintLimits,
): Omit<CompiledCandidateBlueprint, "blueprintDigest"> {
  return Object.freeze({
    protocol: CANDIDATE_BLUEPRINT_PROTOCOL,
    files,
    ...(command === undefined ? {} : { command }),
    ignorePolicyDigest: policyDigest,
    limits,
  });
}

/**
 * Compiles a model proposal into a finite, policy-bound value. The accepted
 * schema intentionally has no oracle, verdict, authority, environment, cwd,
 * timeout, or shell fields.
 */
export function compileCandidateBlueprint(
  input: unknown,
  ignorePolicy: JevyrIgnorePolicy,
  limitOverrides: CandidateBlueprintLimitOverrides = {},
): CompiledCandidateBlueprint {
  if (!isSha256Digest(ignorePolicy.sourceDigest)) fail("integrity", "Candidate ignore policy has an invalid source digest.");
  const limits = normalizeLimits(limitOverrides);
  const record = isPlainRecord(input, "candidate blueprint");
  assertExactKeys(record, ["protocol", "files", "command"], ["protocol", "files"], "candidate blueprint");
  if (record.protocol !== CANDIDATE_BLUEPRINT_PROTOCOL) {
    fail("invalid-shape", `Candidate blueprint protocol must be ${CANDIDATE_BLUEPRINT_PROTOCOL}.`);
  }
  const sourceFiles = jsonArray(record.files, "candidate blueprint files");
  if (sourceFiles.length < 1) fail("invalid-shape", "Candidate blueprint must contain at least one file.");
  if (sourceFiles.length > limits.maxFiles) fail("limit", `Candidate blueprint exceeds ${limits.maxFiles} files.`);
  const files: CandidateBlueprintFile[] = [];
  let totalBytes = 0;
  for (const [index, value] of sourceFiles.entries()) {
    const file = isPlainRecord(value, `candidate blueprint file ${index}`);
    assertExactKeys(file, ["path", "content"], ["path", "content"], `candidate blueprint file ${index}`);
    const path = candidatePath(file.path, limits);
    assertPathAllowed(path, ignorePolicy);
    const compiled = sourceContent(file.content, path, limits);
    totalBytes += compiled.byteLength;
    if (!Number.isSafeInteger(totalBytes) || totalBytes > limits.maxTotalBytes) {
      fail("limit", `Candidate blueprint exceeds ${limits.maxTotalBytes} total UTF-8 file bytes.`);
    }
    files.push(compiled);
  }
  validatePathSet(files);
  files.sort((left, right) => compareText(left.path, right.path));
  const frozenFiles = Object.freeze(files);
  const command = record.command === undefined ? undefined : parseCommand(record.command, limits);
  const payload = blueprintPayload(frozenFiles, command, ignorePolicy.sourceDigest, limits);
  return Object.freeze({
    ...payload,
    blueprintDigest: digestJson(payload as unknown as JsonValue),
  });
}

/** Recompiles every derived field and rejects serialization or memory tampering. */
export function verifyCandidateBlueprint(
  value: unknown,
  ignorePolicy: JevyrIgnorePolicy,
): CompiledCandidateBlueprint {
  const record = isPlainRecord(value, "compiled candidate blueprint");
  assertExactKeys(
    record,
    ["protocol", "files", "command", "ignorePolicyDigest", "limits", "blueprintDigest"],
    ["protocol", "files", "ignorePolicyDigest", "limits", "blueprintDigest"],
    "compiled candidate blueprint",
  );
  if (record.protocol !== CANDIDATE_BLUEPRINT_PROTOCOL || typeof record.blueprintDigest !== "string") {
    fail("integrity", "Compiled candidate blueprint has an invalid protocol or digest.");
  }
  if (record.ignorePolicyDigest !== ignorePolicy.sourceDigest) {
    fail("integrity", "Compiled candidate blueprint is not bound to the supplied ignore policy.");
  }
  const limits = validateCompiledLimits(record.limits);
  const files = jsonArray(record.files, "compiled candidate files");
  const sourceFiles = files.map((value, index) => {
    const file = isPlainRecord(value, `compiled candidate file ${index}`);
    assertExactKeys(file, ["path", "content", "byteLength", "digest"], ["path", "content", "byteLength", "digest"], `compiled candidate file ${index}`);
    if (typeof file.path !== "string" || typeof file.content !== "string"
      || !Number.isSafeInteger(file.byteLength) || !isSha256Digest(file.digest)) {
      fail("integrity", `Compiled candidate file ${index} has invalid derived metadata.`);
    }
    return { path: file.path, content: file.content };
  });
  let sourceCommand: { executable: string; args: readonly unknown[] } | undefined;
  if (record.command !== undefined) {
    const command = isPlainRecord(record.command, "compiled candidate command");
    assertExactKeys(command, ["executable", "args", "shell", "authority"], ["executable", "args", "shell", "authority"], "compiled candidate command");
    if (typeof command.executable !== "string" || command.shell !== false || command.authority !== "proposal-only") {
      fail("integrity", "Compiled candidate command contains forged execution authority.");
    }
    sourceCommand = { executable: command.executable, args: jsonArray(command.args, "compiled candidate command args") };
  }
  const recompiled = compileCandidateBlueprint({
    protocol: CANDIDATE_BLUEPRINT_PROTOCOL,
    files: sourceFiles,
    ...(sourceCommand === undefined ? {} : { command: sourceCommand }),
  }, ignorePolicy, limits);
  if (!isSha256Digest(record.blueprintDigest)
    || canonicalize(record as unknown as JsonValue) !== canonicalize(recompiled as unknown as JsonValue)) {
    fail("integrity", "Compiled candidate blueprint failed canonical digest or derived-field verification.");
  }
  return recompiled;
}

function within(root: string, candidate: string): boolean {
  const path = relative(root, candidate);
  return path === "" || (!path.startsWith(`..${sep}`) && path !== ".." && !isAbsolute(path));
}

function sameIdentity(left: Stats, right: Stats): boolean {
  return left.dev === right.dev && left.ino === right.ino;
}

async function safeDirectory(pathInput: string, context: string): Promise<{ path: string; identity: Stats }> {
  const input = resolve(pathInput);
  let first: Stats;
  try {
    first = await lstat(input);
  } catch (error) {
    return fail("unsafe-destination", `${context} does not exist or cannot be inspected.`, error);
  }
  if (first.isSymbolicLink() || !first.isDirectory()) fail("unsafe-destination", `${context} must be a real directory, not a link or special file.`);
  const path = await realpath(input);
  const second = await lstat(path);
  if (second.isSymbolicLink() || !second.isDirectory() || !sameIdentity(first, second)) {
    fail("unsafe-destination", `${context} changed while it was resolved.`);
  }
  return { path, identity: second };
}

async function ensureParentDirectories(root: string, relativePath: string): Promise<string> {
  const parts = relativePath.split("/");
  parts.pop();
  let current = root;
  for (const part of parts) {
    current = join(current, part);
    if (!within(root, current)) fail("filesystem-integrity", "Candidate parent directory escaped the disposable root.");
    try {
      await mkdir(current, { recursive: false, mode: 0o700 });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
    }
    const info = await lstat(current);
    const resolved = await realpath(current);
    if (info.isSymbolicLink() || !info.isDirectory() || !within(root, resolved)) {
      fail("filesystem-integrity", `Candidate parent became unsafe: ${relativePath}`);
    }
  }
  const target = join(root, ...relativePath.split("/"));
  if (!within(root, target)) fail("filesystem-integrity", "Candidate file escaped the disposable root.");
  return target;
}

async function readStableMaterializedFile(root: string, target: string, maximum: number): Promise<Buffer> {
  const first = await lstat(target);
  if (first.isSymbolicLink() || !first.isFile() || first.size > maximum) {
    fail("filesystem-integrity", `Materialized candidate entry is linked, special, or oversized: ${target}`);
  }
  const resolved = await realpath(target);
  if (!within(root, resolved)) fail("filesystem-integrity", `Materialized candidate entry escaped its root: ${target}`);
  const handle = await open(resolved, "r");
  try {
    const before = await handle.stat();
    if (!before.isFile() || !sameIdentity(first, before) || before.size > maximum) {
      fail("filesystem-integrity", `Materialized candidate entry changed before verification: ${target}`);
    }
    const bytes = await handle.readFile();
    const after = await handle.stat();
    if (!after.isFile() || !sameIdentity(before, after) || before.size !== after.size
      || before.mtimeMs !== after.mtimeMs || bytes.byteLength !== after.size) {
      fail("filesystem-integrity", `Materialized candidate entry changed during verification: ${target}`);
    }
    return bytes;
  } finally {
    await handle.close();
  }
}

async function actualTree(
  root: string,
  expectedFiles: ReadonlyMap<string, CandidateBlueprintFile>,
  expectedDirectories: ReadonlySet<string>,
): Promise<{
  directories: readonly string[];
  files: ReadonlyMap<string, Buffer>;
}> {
  const directories: string[] = [];
  const files = new Map<string, Buffer>();
  const maximumEntries = expectedFiles.size + expectedDirectories.size;
  let visitedEntries = 0;
  const walk = async (directory: string): Promise<void> => {
    const handle = await opendir(directory);
    for await (const child of handle) {
      visitedEntries += 1;
      if (visitedEntries > maximumEntries) {
        fail("filesystem-integrity", "Candidate materialization contains more entries than its compiled blueprint.");
      }
      const target = join(directory, child.name);
      const path = relative(root, target).split(sep).join("/");
      const info = await lstat(target);
      if (info.isSymbolicLink()) fail("filesystem-integrity", `Candidate tree contains a symbolic link or junction: ${path}`);
      if (info.isDirectory()) {
        if (!expectedDirectories.has(path)) {
          fail("filesystem-integrity", `Candidate materialization contains an unexpected directory: ${path}`);
        }
        const resolved = await realpath(target);
        if (!within(root, resolved)) fail("filesystem-integrity", `Candidate directory escaped its root: ${path}`);
        directories.push(path);
        await walk(target);
      } else if (info.isFile()) {
        const expected = expectedFiles.get(path);
        if (expected === undefined) {
          fail("filesystem-integrity", `Candidate materialization contains an unexpected file: ${path}`);
        }
        files.set(path, await readStableMaterializedFile(root, target, expected.byteLength));
      } else {
        fail("filesystem-integrity", `Candidate tree contains a special filesystem entry: ${path}`);
      }
    }
  };
  await walk(root);
  directories.sort(compareText);
  return { directories: Object.freeze(directories), files };
}

function expectedDirectories(files: readonly CandidateBlueprintFile[]): readonly string[] {
  const directories = new Set<string>();
  for (const file of files) {
    const parts = file.path.split("/");
    for (let index = 1; index < parts.length; index += 1) directories.add(parts.slice(0, index).join("/"));
  }
  return Object.freeze([...directories].sort(compareText));
}

/** Verifies that a materialized directory is exactly the compiled candidate tree. */
export async function verifyCandidateMaterialization(
  blueprintValue: unknown,
  rootInput: string,
  ignorePolicy: JevyrIgnorePolicy,
): Promise<CandidateMaterialization> {
  const blueprint = verifyCandidateBlueprint(blueprintValue, ignorePolicy);
  const safeRoot = await safeDirectory(rootInput, "Candidate materialization root");
  const expectedDirectoryList = expectedDirectories(blueprint.files);
  const expectedFileMap = new Map(blueprint.files.map((file) => [file.path, file]));
  const tree = await actualTree(safeRoot.path, expectedFileMap, new Set(expectedDirectoryList));
  if (canonicalize(tree.directories as unknown as JsonValue) !== canonicalize(expectedDirectoryList as unknown as JsonValue)) {
    fail("filesystem-integrity", "Candidate materialization contains missing or unexpected directories.");
  }
  const verifiedFiles: CandidateMaterializedFile[] = [];
  let total = 0;
  if (tree.files.size !== blueprint.files.length) {
    fail("filesystem-integrity", "Candidate materialization contains missing or unexpected files.");
  }
  for (const expected of blueprint.files) {
    const bytes = tree.files.get(expected.path);
    if (bytes === undefined || bytes.byteLength !== expected.byteLength || sha256Digest(bytes) !== expected.digest) {
      fail("filesystem-integrity", `Materialized candidate file failed digest verification: ${expected.path}`);
    }
    total += bytes.byteLength;
    verifiedFiles.push(Object.freeze({ path: expected.path, byteLength: bytes.byteLength, digest: expected.digest }));
  }
  const endingRoot = await lstat(safeRoot.path);
  if (endingRoot.isSymbolicLink() || !endingRoot.isDirectory() || !sameIdentity(safeRoot.identity, endingRoot)) {
    fail("filesystem-integrity", "Candidate materialization root changed during verification.");
  }
  const files = Object.freeze(verifiedFiles);
  const payload = Object.freeze({
    protocol: CANDIDATE_MATERIALIZATION_PROTOCOL,
    blueprintDigest: blueprint.blueprintDigest,
    files,
    fileCount: files.length,
    byteLength: total,
  });
  return Object.freeze({
    ...payload,
    root: safeRoot.path,
    materializationDigest: candidateMaterializationDigest(blueprint.blueprintDigest, files),
    ...(blueprint.command === undefined ? {} : { commandProposal: blueprint.command }),
  });
}

/**
 * Writes only into a fresh random child of the supplied real parent. Files use
 * exclusive creation, and the complete tree is re-read and rehashed before it
 * is returned. A failed write is removed because this function created and
 * exclusively owns that random directory.
 */
export async function materializeCandidateBlueprint(
  blueprintValue: unknown,
  disposableParentInput: string,
  ignorePolicy: JevyrIgnorePolicy,
): Promise<CandidateMaterialization> {
  const blueprint = verifyCandidateBlueprint(blueprintValue, ignorePolicy);
  const parent = await safeDirectory(disposableParentInput, "Candidate disposable parent");
  let root: string | undefined;
  try {
    root = await mkdtemp(join(parent.path, "jevyr-candidate-"));
    await chmod(root, 0o700);
    const rootInfo = await lstat(root);
    const rootResolved = await realpath(root);
    if (rootInfo.isSymbolicLink() || !rootInfo.isDirectory() || !within(parent.path, rootResolved)) {
      fail("unsafe-destination", "Fresh candidate directory did not resolve inside its declared parent.");
    }
    for (const file of blueprint.files) {
      const target = await ensureParentDirectories(rootResolved, file.path);
      const bytes = Buffer.from(file.content, "utf8");
      const handle = await open(target, "wx", 0o600);
      try {
        await handle.writeFile(bytes);
        await handle.sync();
        const stats = await handle.stat();
        if (!stats.isFile() || stats.size !== file.byteLength) {
          fail("filesystem-integrity", `Candidate file changed while it was written: ${file.path}`);
        }
      } finally {
        await handle.close();
      }
    }
    return await verifyCandidateMaterialization(blueprint, rootResolved, ignorePolicy);
  } catch (error) {
    if (root !== undefined && within(parent.path, root)) await rm(root, { recursive: true, force: true });
    if (error instanceof CandidateBlueprintError) throw error;
    return fail("filesystem-integrity", "Candidate materialization failed.", error);
  }
}
