import { createElement as h, type ReactElement } from "react";
import { Box, Text, render, useInput } from "ink";
import type { JevyrClient, LiveFrame, MetabolicOffer } from "@jevyr/sdk";
import { WatchTuiController, parseTuiQuantity, type WatchSnapshot, type TuiKey } from "./tui-controller.js";
export { WatchTuiController, parseTuiQuantity } from "./tui-controller.js";
export type { WatchSnapshot } from "./tui-controller.js";

/** Strip terminal controls from untrusted public summaries, preserving ordinary text. */
export function terminalText(value: string): string {
  return value.replace(/\x1b(?:\[[0-?]*[ -/]*[@-~]|\][^\x07]*(?:\x07|\x1b\\))/gu, "")
    .replace(/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/gu, " ");
}

export function metabolicCostText(offer:MetabolicOffer,quantity=1):string {
  const names:Record<string,string>={maxMindInvocations:"calls",maxInputTokens:"input tokens",maxOutputTokens:"output tokens",maxWallMillis:"wall ms",maxGeneratedBytes:"generated bytes",maxForgeCpuMillis:"Forge CPU ms",maxForgeWallMillis:"Forge wall ms",maxMemorySeconds:"memory seconds",maxWritableBytes:"writable bytes",maxWritableInodes:"inodes",maxArtifactBytes:"artifact bytes",maxTotalAssayCost:"assay units"};
  return Object.entries(offer.unitCostCeiling).filter(([,amount])=>amount>0).map(([name,amount])=>`${names[name]??name}=${BigInt(amount)*BigInt(quantity)}`).join(" · ")||"zero across declared resource dimensions";
}

export function WatchView({ snapshot, onInput }: { snapshot: WatchSnapshot; onInput:(text:string,key:TuiKey)=>void }): ReactElement {
  useInput((input,key)=>onInput(input,key),{isActive:snapshot.interactive});
  const latest = snapshot.frames.at(-1);
  const text=(value:string)=>terminalText(value).slice(0,2048);
  const limit=Math.max(3,Math.min(12,(process.stdout.rows??24)-12));
  const claims=snapshot.claims.slice(snapshot.panel==="claims"?snapshot.offset:0,snapshot.panel==="claims"?snapshot.offset+limit:3);
  const lanes=snapshot.lanes.slice(snapshot.panel==="lanes"?snapshot.offset:0,snapshot.panel==="lanes"?snapshot.offset+limit:3);
  const content:ReactElement[]=[];
  if(snapshot.panel==="overview"||snapshot.panel==="claims") {
    content.push(h(Text,{key:"claims",bold:true},`Claims · ${snapshot.claims.length}${snapshot.claims.length?` (from ${snapshot.panel==="claims"?snapshot.offset+1:1})`:""}`));
    if(!claims.length)content.push(h(Text,{key:"claims-empty",dimColor:true},"No sealed obligations or public proposals loaded"));
    claims.forEach(claim=>content.push(h(Text,{key:`${claim.authority}/${claim.id}`,wrap:"truncate-end"},`[${claim.authority}] ${text(claim.statement)} · assay reports ${claim.passed} passed/${claim.failed} failed/${claim.other} other`)));
  }
  if(snapshot.panel==="overview"||snapshot.panel==="lanes") {
    content.push(h(Text,{key:"lanes",bold:true},`Lanes · ${snapshot.lanes.length} observed commitments`));
    if(!lanes.length)content.push(h(Text,{key:"lanes-empty",dimColor:true},"No committed lane receipts observed"));
    lanes.forEach(lane=>content.push(h(Text,{key:lane.id,wrap:"truncate-end"},`${text(lane.provider)}/${text(lane.model)} · ${text(lane.status)} · seed ${text(lane.seedEnforcement)}`)));
  }
  if(snapshot.panel==="overview"||snapshot.panel==="balls") {
    content.push(h(Text,{key:"balls",bold:true},`Metabolism · ${text(snapshot.offersState)}`));
    snapshot.offers?.offers.forEach((offer,index)=>content.push(h(Text,{key:offer.ballId,wrap:"truncate-end",...(snapshot.selection?.ballId===offer.ballId?{color:"yellow" as const}:{})},`${index+1} ${offer.kind} · quantity 1–${offer.maxQuantity} · unit ceiling ${metabolicCostText(offer)}`)));
    const selected=snapshot.selection;
    if(selected) {
      let quantity:number|undefined;try{quantity=parseTuiQuantity(snapshot.quantity,selected.maxQuantity);}catch{/* Incomplete input is not permission. */}
      content.push(h(Text,{key:"effect"},text(selected.promisedEffect)));
      content.push(h(Text,{key:"scope",dimColor:true},`Measured scope: ${text(selected.calibration.scope)} · ${selected.calibration.pairedSeeds} paired seeds · doses ${selected.calibration.doses.join(",")}`));
      content.push(h(Text,{key:"intervals",dimColor:true},`95% differences · recall [${selected.calibration.recallDifference.lower}, ${selected.calibration.recallDifference.upper}] · reproducibility [${selected.calibration.reproducibilityDifference.lower}, ${selected.calibration.reproducibilityDifference.upper}]`));
      content.push(h(Text,{key:"cost"},`${quantity===undefined?"Unit":`Quantity ${quantity}`} cost ceiling: ${metabolicCostText(selected,quantity??1)}`));
      content.push(h(Text,{key:"quantity",bold:true,color:"yellow"},`${selected.kind} quantity [1–${selected.maxQuantity}]: ${snapshot.quantity||"_"}${snapshot.submitting?" · sending once":" · Enter sends / Esc cancels"}`));
    }
  }
  return h(Box, { flexDirection: "column", borderStyle: "round", paddingX: 1 },
    h(Text, { bold: true, color: "cyan" }, `Jevyr · ${terminalText(snapshot.caseId)}`),
    h(Text, {}, `${latest?.event.stage ?? "CONNECTING"} · ${snapshot.observed} observed events · ${latest?.transport ?? "waiting"}`),
    h(Text,{dimColor:true},`${snapshot.authentication==="seal-verified"?"Seal authenticated":"Seal not yet authenticated"} · ${snapshot.control} · events since cursor ${snapshot.fromCursor}`),
    h(Text, { dimColor: true }, "Live claim/assay reports have hash-chain continuity; evidence is not replayed here."),
    h(Text,{dimColor:true},`Tab: overview / claims / lanes / balls · current ${snapshot.panel} · ↑/↓ scroll`),
    ...content,
    ...(snapshot.panel==="overview"?snapshot.frames.slice(-2).map(frame=>h(Text,{key:`event-${frame.cursor}`,dimColor:true,wrap:"truncate-end"},`${frame.cursor} ${frame.event.stage} · ${text("summary" in frame.event.payload?String(frame.event.payload.summary):frame.event.kind)}`)):[]),
    h(Text,{...(snapshot.uncertain?{color:"yellow" as const}:{}),wrap:"wrap"},text(snapshot.message)),
    h(Text,{dimColor:true},snapshot.control==="juggler"&&snapshot.interactive?"1–5 choose offered ball · type quantity + Enter · r refreshes signed history":"Read-only view: no live additions available"),
    h(Text, { dimColor: true }, "q / Esc closes the observer; the sealed Case keeps running."),
  );
}

/** The controller exposes only the finite quantity route after sealed Juggler authorization. */
export function createWatchTui(caseId: string, onQuit: () => void, client:JevyrClient, options:{cursor?:number}={}) {
  let closed=false;
  const onInput=(text:string,key:TuiKey)=>{void controller.input(text,key);};
  const quit=()=>{controller.close();onQuit();};
  const controller=new WatchTuiController(caseId,client,snapshot=>{if(!closed)instance.rerender(h(WatchView,{snapshot,onInput}));},quit,{interactive:Boolean(process.stdin.isTTY&&process.stdout.isTTY),...options});
  const instance = render(h(WatchView, { snapshot:controller.snapshot, onInput }), { exitOnCtrlC: false, patchConsole: false });
  return {
    ready:controller.start(),
    push(frame: LiveFrame) {controller.push(frame);},
    close() {if(closed)return;closed=true;controller.close();instance.unmount();},
  };
}
